### ISSUE TITLE
ConfigParser.NoSectionError: No section: 'color'

### ISSUE THREAD

**Issue by jspiro** [karandesai-96/yolog#11] opened 2016-07-21 19:00 UTC
```
$ yolog
Traceback (most recent call last):
  File "/usr/local/bin/yolog", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/yolog/main.py", line 26, in main
    yolog_gen = YologGenerator(config_filepath)
  File "/usr/local/lib/python2.7/site-packages/yolog/yolog_generator.py", line 79, in __init__
    getattr(self, self.config.get("color", "hash")), RESET)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'color'
```

This is a clean pip installation. What am I doing wrong?

**Comment by kdexd** [comment] 2016-07-22 01:47
Hi @jspiro I tried reproducing it, but a clean installation of `pip` on my laptop gave no such error. Can you give me this information:
1. Contents and read/write permissions of the file `~/.yolog/config.ini`.
2. The complete log of pip installation.

**Comment by jpmhouston** [comment] 2016-07-25 14:54
I'm getting this too, `~/.yolog/config.ini` didn't exist, I since did mkdir + touch to put an empty file there FWIW, with no effect on the error. I'm using fish shell, OS X El Cap. 10.11.5. Here's a verbose install log & full error output:

```
> pip install yolog --verbose
Collecting yolog
  1 location(s) to search for versions of yolog:
  * https://pypi.python.org/simple/yolog/
  Getting page https://pypi.python.org/simple/yolog/
  Looking up "https://pypi.python.org/simple/yolog/" in the cache
  Current age based on date: 166
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 166
  Analyzing links from page https://pypi.python.org/simple/yolog/
    Found link https://pypi.python.org/packages/2e/9b/04b7b95bd630d8d68aeeb57bba95b92f9de77d3cf47d1bfaf28c56924299/yolog-0.1.3.tar.gz#md5=c52da07c9b1473d07f092c0b2c4555a2 (from https://pypi.python.org/simple/yolog/), version: 0.1.3
    Found link https://pypi.python.org/packages/6b/9a/2223234e096d857bfb27e7a368ede2306dbde2d524f2304bbe6593596ef6/yolog-0.1.1.tar.gz#md5=bd7027da8b48408ecdd95bcdaa31da0f (from https://pypi.python.org/simple/yolog/), version: 0.1.1
    Found link https://pypi.python.org/packages/78/c8/89e89dea41f0978e5712ea7a2e49bc1a0b4644a9870f39fd42ee164bb4b0/yolog-0.2.0.tar.gz#md5=6069a3c28809c2c7b268a82cf5fc3aef (from https://pypi.python.org/simple/yolog/), version: 0.2.0
    Found link https://pypi.python.org/packages/7e/45/c0cb16ac01dd7fcb7ad0515a274e310b1df374b645cb76034faae504ffbf/yolog-0.2.1.tar.gz#md5=3f739a483e88f4ab8215c4821d170d19 (from https://pypi.python.org/simple/yolog/), version: 0.2.1
    Found link https://pypi.python.org/packages/af/d5/8fcd8c29fe80827bad59b1eb92d05d296fd9e7c181cfe527294470d025a6/yolog-0.3.tar.gz#md5=d0f4f9bab68e5c31f7741ea0be0fae31 (from https://pypi.python.org/simple/yolog/), version: 0.3
    Found link https://pypi.python.org/packages/ea/e8/143d6acdceb5cdc0d7bebf119a5f7d5e96315887916e0ec4b2e0ed1a59d2/yolog-0.2.2.tar.gz#md5=7248035e61bc01b38337589269c9ac72 (from https://pypi.python.org/simple/yolog/), version: 0.2.2
  Using version 0.3 (newest of versions: 0.1.1, 0.1.3, 0.2.0, 0.2.1, 0.2.2, 0.3)
  Using cached wheel link: file:///Users/pierre/Library/Caches/pip/wheels/d3/bd/fe/4814c111595bd56ea3a2eaca6074ad939e1129c69f47be02a5/yolog-0.3-cp27-none-any.whl
Installing collected packages: yolog

  changing mode of /usr/local/bin/yolog to 755
Successfully installed yolog-0.3
Cleaning up...
```

```
Traceback (most recent call last):
  File "/usr/local/bin/yolog", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/yolog/main.py", line 26, in main
    yolog_gen = YologGenerator(config_filepath)
  File "/usr/local/lib/python2.7/site-packages/yolog/yolog_generator.py", line 79, in __init__
    getattr(self, self.config.get("color", "hash")), RESET)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'color'
```

**Comment by kdexd** [comment] 2016-07-25 15:07
I am not having any facility to check compatibility with OSX, so `yolog` is right now supported on Linux distributions. Have a look at `setup.py` file and see if you can do platform checks and ensure compatibility of yolog in OSX. I will be happily accepting a PR.

My `config.ini` file looks like this, and it is generated by `setup.py`:

``` ini
[color]
hash = YELLOW
author = BLUE
date = GREEN
refs = RED
description = WHITE
```

**Comment by jpmhouston** [comment] 2016-07-25 17:20
With that pasted into my config.ini `yolog` is working nicely. I probably have no time to investigate the `setup.py` on macOS over the next few weeks, hopefully someone else can take a look and create a PR.

**Comment by kdexd** [comment] 2016-07-25 17:39
Okay no worries. Glad that it works fine on your machine now. :smile:

**Comment by kdexd** [comment] 2016-07-27 12:41
I'll close this issue for now and take up OSX compatibility solving later. Thanks :+1:

**Closed as completed by kdexd** 2016-07-27 12:41 UTC
